[cmd_duration]
show_milliseconds = true

[directory]
truncation_length = 8

[hostname]
ssh_only = false
format = '[@](dimmed red)[$hostname]($style) in '
style = 'yellow'

[shlvl]
disabled = false
threshold = 3
symbol = '↕️'

[status]
disabled = false
pipestatus = true

[time]
disabled = false

[username]
format = '[$user]($style)'
style_user = 'dimmed yellow'
aliases = { 'yacoob' = '' }
