"$schema" = 'https://starship.rs/config-schema.json'

[cmd_duration]
show_milliseconds = true

[directory]
truncation_length = 8

[env_var.WSL_PROMPT_DISTRO_NAME]
symbol = '󰌽'
description = 'WSL Distribution name, if different than Debian'
format = '[$symbol $env_value ]($style)'
style = 'blue'

[hostname]
ssh_only = false
format = '[@](dimmed red)[$hostname]($style) in '
style = 'yellow'

[shlvl]
disabled = false
threshold = 3
symbol = ' '

[status]
disabled = false
pipestatus = true

[time]
disabled = false

[username]
aliases = { 'yacoob' = '' }
format = '[$user]($style)'
style_user = 'dimmed yellow'
