name: Build and push image to Docker Hub

on:
  # Build for all git pushes, push and mark as 'latest' only for
  # main branch.
  push:
  # For pull requests, build but don't push.
  pull_request:
  # Build and push if triggered manually.

jobs:
  build:
    name: Build and optionally push the image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Work out docker tags
        uses: crazy-max/ghaction-docker-meta@v1
        id: docker_meta
        with:
          images: yacoob/interactive
          # Tag as 'latest' only if it's a push to the main branch.
          tag-match-latest: ${{ github.ref == 'refs/heads/master' }}
          tag-sha: true
      - name: Set up docker builder (buildx)
        uses: docker/setup-buildx-action@v1
      - name: Log in to docker hub
        # Skip registry push for pull_requests.
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and optionally push the base version
        uses: docker/build-push-action@v2
        with:
          target: base
          context: .
          file: workarea/conf/docker/Dockerfile
          # Skip registry push for pull_requests.
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
      - name: Build and optionally push the vim version
        uses: docker/build-push-action@v2
        with:
          target: vim
          context: .
          file: workarea/conf/docker/Dockerfile
          # Skip registry push for pull_requests.
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
