name: Build and push image to Docker Hub

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and push image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +%s)" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push base version
        uses: docker/build-push-action@v2
        with:
          file: workarea/conf/docker/Dockerfile
          target: base
          tags: |
            yacoob/interactive:latest
            yacoob/interactive:latest-${{ env.NOW }}
            yacoob/interactive:base
            yacoob/interactive:base-${{ env.NOW }}
      - name: Build and push vim version
        uses: docker/build-push-action@v2
        with:
          file: workarea/conf/docker/Dockerfile
          target: vim
          tags: |
            yacoob/interactive:vim
            yacoob/interactive:vim-${{ env.NOW }}
