name: Build and push image to Docker Hub

on:
  # Build for all git pushes, push and mark as 'latest' only for
  # main branch.
  push:
  # For pull requests, build but don't push.
  pull_request:
  # Build and push if triggered manually.

env:
  REPO_IS_DETACHED: ${{ github.event_name == 'pull_request' }}
  PUSH_TO_MASTER: ${{ github.event_name == 'push' && endsWith(github.ref, '/master') }}

jobs:
  build:
    name: Build and optionally push the image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Work out docker tags
        uses: crazy-max/ghaction-docker-meta@v1
        id: docker_meta
        with:
          images: yacoob/interactive
          tag-sha: true
      - name: Set branch name as env variable
        run: |
          export _BRANCH=${{ github.head_ref || github.ref }}
          echo "CONF_BRANCH=${_BRANCH##*/}" >> $GITHUB_ENV
      - name: Debug dump
        uses: crazy-max/ghaction-dump-context@v1
      - name: Set up docker builder (buildx)
        uses: docker/setup-buildx-action@v1
      - name: Log in to docker hub
        # Skip registry push for pull_requests.
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and optionally push the base version
        uses: docker/build-push-action@v2
        with:
          target: base
          context: .
          file: workarea/conf/docker/Dockerfile
          build-args: |
            CONF_BRANCH=${{ env.CONF_BRANCH }}
            REPO_IS_DETACHED=${{ env.REPO_IS_DETACHED }}
          # Skip registry push for pull_requests.
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          tags: |
            ${{ steps.docker_meta.outputs.tags }}
            ${{ env.PUSH_TO_MASTER == 'true' && 'yacoob/interactive:latest' || ''}}
      - name: Build and optionally push the vim version
        uses: docker/build-push-action@v2
        with:
          target: vim
          context: .
          file: workarea/conf/docker/Dockerfile
          build-args: |
            CONF_BRANCH=${{ env.CONF_BRANCH }}
            REPO_IS_DETACHED=${{ env.REPO_IS_DETACHED }}
          # Skip registry push for pull_requests.
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          tags: |
            ${{ steps.docker_meta.outputs.tags }}
            ${{ env.PUSH_TO_MASTER == 'true' && 'yacoob/interactive:latest' || ''}}
  ping-others:
    name: Notify other repositories about new version of the base image.
    runs-on: ubuntu-latest
    # Only ping others on pushes to main branch.
    if: github.event_name == 'push' && endsWith(github.ref, '/master')
    # Don't ping if build step failed.
    needs: build
    steps:
      - name: Ping yacoob/gcu
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PUBLIC_REPO_TOKEN }}
          repository: yacoob/gcu
          event-type: dependency-updated
